# Generated by Django 5.0.1 on 2025-06-02 01:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='MPAN must be exactly 13 digits', regex='^\\d{13}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mpan'],
            },
        ),
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['filename'], name='flow_proces_filenam_34c5ac_idx'), models.Index(fields=['imported_at'], name='flow_proces_importe_e81fd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('meter_type', models.CharField(choices=[('single', 'Single Rate'), ('economy7', 'Economy 7'), ('smart', 'Smart Meter')], default='single', max_length=20)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='flow_processor.meterpoint')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(db_index=True)),
                ('reading_time', models.TimeField(blank=True, null=True)),
                ('register_id', models.CharField(default='01', max_length=10)),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_type', models.CharField(choices=[('actual', 'Actual'), ('estimated', 'Estimated'), ('customer', 'Customer')], default='actual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='flow_processor.flowfile')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='flow_processor.meter')),
            ],
            options={
                'ordering': ['-reading_date', '-reading_time'],
            },
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['serial_number'], name='flow_proces_serial__bdea1f_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['meter_point'], name='flow_proces_meter_p_d30277_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['meter', 'reading_date'], name='flow_proces_meter_i_9811ac_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['reading_date'], name='flow_proces_reading_3751c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('meter', 'reading_date', 'reading_time', 'register_id')},
        ),
    ]
